### ISSUE TITLE
Some questions about entropymodel

### ISSUE THREAD

**Issue by cyhhhhhhit** [RenYang-home/RLVC#5]
Hi, I'm trying to train my own RLVC model, but there are some questions I'm not sure.
Do we need to compress the second frame via tfc.entropy_bottleneck even RPM is performed?

**Comment by RenYang-home** [comment]
Yes, because RPM needs temporal prior, but the second frame (the first P-frame) doesn't have previous latents, so it is not compressed by RPM.--Dr. Ren Yanghttps://renyang-home.github.io/Computer Vision Laboratory | ETH ZürichSternwartstrasse 7 | ETF D 114.2 | 8092 Zürich, Switzerland在 13.01.2023，18:27，cyhhhhhhit ***@***.***> 写道：﻿
Hi, I'm trying to train my own RLVC model, but there are some questions I'm not sure.
Do we need to compress the second frame via tfc.entropy_bottleneck even RPM is performed?
